name: Discord Notify

on:
  push:
  pull_request:
  issues:
  issue_comment:
  release:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"📦 Repository event ${{ github.repository }} | Event: ${{ github.event_name }} | Author: ${{ github.actor }} | Branch: ${{ github.ref_name }} | https://github.com/${{ github.repository }}\"}"

