name: Discord Notify

on:
  push:
  pull_request:
  issues:
  issue_comment:
  release:
  workflow_run:
    workflows: ["*"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        run: |
          curl -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d '{
              "content": "📦 Evento no repositório **'${{ github.repository }}'**\n\
              • Event: **'${{ github.event_name }}'**\n\
              • Author: **'${{ github.actor }}'**\n\
              • Branch: **'${{ github.ref_name }}'**\n\
              • Link: https://github.com/'${{ github.repository }}'"
            }'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
